include:
  - ./db/prod/docker-compose.yml

services:
  web:
    env_file:
      - ./prod.env
    volumes:
      - ./prod.env:/app/prod.env
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: .
    ports:
      - "12321:12321"
