ktor:
  application:
    # noinspection KtorYamlConfig
    modules:
      - buildService.ApplicationKt.module
  deployment:
    development: true
    port: 12321
    host: 0.0.0.0
    shutdown:
      url: "shutdown"
isTesting: false
