ktor:
  application:
    # noinspection KtorYamlConfig
    modules:
      - buildService.ApplicationKt.module
  deployment:
    development: true
    port: 8080
    host: localhost
    shutdown:
      url: "shutdown"
isTesting: false
